apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tamarshnirer/example-gitops.git
    targetRevision: HEAD
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:  
      selfHeal: true
      prune: true