apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shorten-url
  name: shorten-url-service
spec:
  ports:
    - name: port
      port: 5000 
      protocol: TCP
      targetPort: 5000
      nodePort: 32450 
  selector:
<<<<<<< HEAD:weather-svc.yaml
    app: weather-app
  type: NodePort
=======
    app: shorten-url
  type: NodePort

>>>>>>> cf5498159d208a06091f6e1052d7f26757d3f709:shorten-url-svc.yaml
