apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: shorten-url
  name: shorten-url-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shorten-url
  template:
    metadata:
      labels:
        app: shorten-url
    spec:
      containers:
      - image: tamarshnirer/shorten-url:1.0.5
        name: shorten-url-container
        ports:
          - containerPort: 8000
