apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weather-app
  name: weather-service
spec:
  ports:
    - name: port
      port: 5000 
      protocol: TCP
      targetPort: 5000
      nodePort: 32450 
  selector:
    app: weather-app
  type: NodePort